version: '3'

services:
  vpn:
    image: mrchupatek/vpn_l2tp_ipsec:0.5
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    entrypoint: bash -c "/opt/src/vpnsetup.sh && tail -f /dev/null"
    hostname: vpn-server
    container_name: vpn-server
